<?php 
    add_action( 'init', function() {
        register_post_type( 'apartment', array(
        'labels' => array(
            'name' => 'Apartments',
            'singular_name' => 'Apartment',
            'menu_name' => 'Apartments',
            'all_items' => 'All Apartments',
            'edit_item' => 'Edit Apartment',
            'view_item' => 'View Apartment',
            'view_items' => 'View Apartments',
            'add_new_item' => 'Add New Apartment',
            'new_item' => 'New Apartment',
            'parent_item_colon' => 'Parent Apartment:',
            'search_items' => 'Search Apartments',
            'not_found' => 'No apartments found',
            'not_found_in_trash' => 'No apartments found in Trash',
            'archives' => 'Apartment Archives',
            'attributes' => 'Apartment Attributes',
            'insert_into_item' => 'Insert into apartment',
            'uploaded_to_this_item' => 'Uploaded to this apartment',
            'filter_items_list' => 'Filter apartments list',
            'filter_by_date' => 'Filter apartments by date',
            'items_list_navigation' => 'Apartments list navigation',
            'items_list' => 'Apartments list',
            'item_published' => 'Apartment published.',
            'item_published_privately' => 'Apartment published privately.',
            'item_reverted_to_draft' => 'Apartment reverted to draft.',
            'item_scheduled' => 'Apartment scheduled.',
            'item_updated' => 'Apartment updated.',
            'item_link' => 'Apartment Link',
            'item_link_description' => 'A link to a apartment.',
        ),
        'public' => true,
        'show_in_rest' => true,
        'supports' => array(
            0 => 'title',
            1 => 'editor',
            2 => 'thumbnail',
        ),
        'delete_with_user' => false,
    ) );
    } );
    
    if( function_exists('acf_add_local_field_group') ):

        acf_add_local_field_group(array(
            'key' => 'group_65259e321715f',
            'title' => 'Apartment fields',
            'fields' => array(
                array(
                    'key' => 'field_65259e3234b03',
                    'label' => 'Title',
                    'name' => 'title',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'aria-label' => '',
                    'default_value' => '',
                    'maxlength' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                ),
                array(
                    'key' => 'field_65259e4734b04',
                    'label' => 'Description',
                    'name' => 'description',
                    'type' => 'wysiwyg',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'aria-label' => '',
                    'default_value' => '',
                    'maxlength' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                ),
                array(
                    'key' => 'field_65259f54fe76f',
                    'label' => 'Gallery',
                    'name' => 'gallery',
                    'type' => 'gallery',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'aria-label' => '',
                    'return_format' => 'url',
                    'library' => 'all',
                    'min' => '',
                    'max' => '',
                    'min_width' => '',
                    'min_height' => '',
                    'min_size' => '',
                    'max_width' => '',
                    'max_height' => '',
                    'max_size' => '',
                    'mime_types' => '',
                    'insert' => 'append',
                    'preview_size' => 'medium',
                ),
                array(
                    'key' => 'field_6525a1ffc3be0',
                    'label' => 'Pet Policy',
                    'name' => 'pet_policy',
                    'type' => 'radio',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'aria-label' => '',
                    'choices' => array(
                        'Allowed' => 'Allowed',
                        'Not allowed' => 'Not allowed',
                    ),
                    'default_value' => '',
                    'return_format' => 'value',
                    'allow_null' => 0,
                    'other_choice' => 0,
                    'layout' => 'vertical',
                    'save_other_choice' => 0,
                ),
                array(
                    'key' => 'field_6525a22bc3be1',
                    'label' => 'Features',
                    'name' => 'features',
                    'type' => 'checkbox',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'aria-label' => '',
                    'choices' => array(
                        'Balcony' => 'Balcony',
                        'Swimming pool' => 'Swimming pool',
                        'Gym' => 'Gym',
                        'Garage' => 'Garage',
                        'Private Terrace' => 'Private Terrace',
                        'High Ceilings' => 'High Ceilings',
                        'Elevator' => 'Elevator',
                        'Private Storage Included' => 'Private Storage Included',
                        'City Views' => 'City Views',
                        'Oversized Windows' => 'Oversized Windows',
                    ),
                    'default_value' => array(
                    ),
                    'return_format' => 'value',
                    'allow_custom' => 0,
                    'layout' => 'vertical',
                    'toggle' => 0,
                    'save_custom' => 0,
                ),
                array(
                    'key' => 'field_6525a263c3be2',
                    'label' => 'Furnished',
                    'name' => 'furnished',
                    'type' => 'select',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'aria-label' => '',
                    'choices' => array(
                        'Yes' => 'Yes',
                        'No' => 'No',
                    ),
                    'default_value' => false,
                    'return_format' => 'value',
                    'multiple' => 0,
                    'allow_null' => 0,
                    'ui' => 0,
                    'ajax' => 0,
                    'placeholder' => '',
                ),
                array(
                    'key' => 'field_6525a2aec3be3',
                    'label' => 'Bedrooms',
                    'name' => 'bedrooms',
                    'type' => 'range',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'aria-label' => '',
                    'default_value' => 2,
                    'min' => '',
                    'max' => '',
                    'step' => '',
                    'prepend' => '',
                    'append' => '',
                ),
                array(
                    'key' => 'field_6525a2e8c3be4',
                    'label' => 'Bathrooms',
                    'name' => 'bathrooms',
                    'type' => 'range',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'aria-label' => '',
                    'default_value' => 1,
                    'min' => '',
                    'max' => '',
                    'step' => '',
                    'prepend' => '',
                    'append' => '',
                ),
                array(
                    'key' => 'field_6525a2f9c3be5',
                    'label' => 'Price',
                    'name' => 'price',
                    'type' => 'number',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'aria-label' => '',
                    'default_value' => '',
                    'min' => '',
                    'max' => '',
                    'placeholder' => '',
                    'step' => '',
                    'prepend' => '',
                    'append' => '$',
                ),
                array(
                    'key' => 'field_65437d08c3e5e',
                    'label' => 'Area',
                    'name' => 'area',
                    'type' => 'number',
                    'instructions' => 'Enter the area in square meters.',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'aria-label' => '',
                    'default_value' => '',
                    'min' => '',
                    'max' => '',
                    'placeholder' => '',
                    'step' => '',
                    'prepend' => '',
                    'append' => 'sq m',
                ),
                array(
                    'key' => 'field_654543c01b54a',
                    'label' => 'Address',
                    'name' => 'address',
                    'type' => 'google_map',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'aria-label' => '',
                    'center_lat' => '',
                    'center_lng' => '',
                    'zoom' => '',
                    'height' => '',
                ),
            ),
            'location' => array(
                array(
                    array(
                        'param' => 'post_type',
                        'operator' => '==',
                        'value' => 'apartment',
                    ),
                ),
            ),
            'menu_order' => 0,
            'position' => 'normal',
            'style' => 'default',
            'label_placement' => 'top',
            'instruction_placement' => 'label',
            'hide_on_screen' => '',
            'active' => true,
            'description' => '',
            'show_in_rest' => 0,
        ));
        
        endif;

       